/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents.$documentId'
import { Route as ScansIndexRouteImport } from './routes/scans.index'
import { Route as ScansScanIdRouteImport } from './routes/scans.$scanId'
import { Route as ScansUploadRouteImport } from './routes/scans.upload'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsCatalogRouteImport } from './routes/settings.$catalog'
import { Route as ScansScanIdReviewRouteImport } from './routes/scans.$scanId_.review'
import { Route as SettingsCatalogNewRouteImport } from './routes/settings.$catalog_.new'
import { Route as SettingsCatalogEntryIdEditRouteImport } from './routes/settings.$catalog_.$entryId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => DocumentsRoute,
} as any)
const ScansIndexRoute = ScansIndexRouteImport.update({
  id: '/scans/',
  path: '/scans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansScanIdRoute = ScansScanIdRouteImport.update({
  id: '/scans/$scanId',
  path: '/scans/$scanId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansUploadRoute = ScansUploadRouteImport.update({
  id: '/scans/upload',
  path: '/scans/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCatalogRoute = SettingsCatalogRouteImport.update({
  id: '/$catalog',
  path: '/$catalog',
  getParentRoute: () => SettingsRoute,
} as any)
const ScansScanIdReviewRoute = ScansScanIdReviewRouteImport.update({
  id: '/scans/$scanId_/review',
  path: '/scans/$scanId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCatalogNewRoute = SettingsCatalogNewRouteImport.update({
  id: '/$catalog_/new',
  path: '/$catalog/new',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCatalogEntryIdEditRoute =
  SettingsCatalogEntryIdEditRouteImport.update({
    id: '/$catalog_/$entryId/edit',
    path: '/$catalog/$entryId/edit',
    getParentRoute: () => SettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/scans/$scanId': typeof ScansScanIdRoute
  '/scans/upload': typeof ScansUploadRoute
  '/settings/$catalog': typeof SettingsCatalogRoute
  '/scans/': typeof ScansIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/scans/$scanId/review': typeof ScansScanIdReviewRoute
  '/settings/$catalog/new': typeof SettingsCatalogNewRoute
  '/settings/$catalog/$entryId/edit': typeof SettingsCatalogEntryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/scans/$scanId': typeof ScansScanIdRoute
  '/scans/upload': typeof ScansUploadRoute
  '/settings/$catalog': typeof SettingsCatalogRoute
  '/scans': typeof ScansIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/scans/$scanId/review': typeof ScansScanIdReviewRoute
  '/settings/$catalog/new': typeof SettingsCatalogNewRoute
  '/settings/$catalog/$entryId/edit': typeof SettingsCatalogEntryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/scans/$scanId': typeof ScansScanIdRoute
  '/scans/upload': typeof ScansUploadRoute
  '/settings/$catalog': typeof SettingsCatalogRoute
  '/scans/': typeof ScansIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/scans/$scanId_/review': typeof ScansScanIdReviewRoute
  '/settings/$catalog_/new': typeof SettingsCatalogNewRoute
  '/settings/$catalog_/$entryId/edit': typeof SettingsCatalogEntryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents'
    | '/settings'
    | '/api/$'
    | '/documents/$documentId'
    | '/scans/$scanId'
    | '/scans/upload'
    | '/settings/$catalog'
    | '/scans/'
    | '/settings/'
    | '/scans/$scanId/review'
    | '/settings/$catalog/new'
    | '/settings/$catalog/$entryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documents'
    | '/api/$'
    | '/documents/$documentId'
    | '/scans/$scanId'
    | '/scans/upload'
    | '/settings/$catalog'
    | '/scans'
    | '/settings'
    | '/scans/$scanId/review'
    | '/settings/$catalog/new'
    | '/settings/$catalog/$entryId/edit'
  id:
    | '__root__'
    | '/'
    | '/documents'
    | '/settings'
    | '/api/$'
    | '/documents/$documentId'
    | '/scans/$scanId'
    | '/scans/upload'
    | '/settings/$catalog'
    | '/scans/'
    | '/settings/'
    | '/scans/$scanId_/review'
    | '/settings/$catalog_/new'
    | '/settings/$catalog_/$entryId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ScansScanIdRoute: typeof ScansScanIdRoute
  ScansUploadRoute: typeof ScansUploadRoute
  ScansIndexRoute: typeof ScansIndexRoute
  ScansScanIdReviewRoute: typeof ScansScanIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/scans/': {
      id: '/scans/'
      path: '/scans'
      fullPath: '/scans/'
      preLoaderRoute: typeof ScansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/$scanId': {
      id: '/scans/$scanId'
      path: '/scans/$scanId'
      fullPath: '/scans/$scanId'
      preLoaderRoute: typeof ScansScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/upload': {
      id: '/scans/upload'
      path: '/scans/upload'
      fullPath: '/scans/upload'
      preLoaderRoute: typeof ScansUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/$catalog': {
      id: '/settings/$catalog'
      path: '/$catalog'
      fullPath: '/settings/$catalog'
      preLoaderRoute: typeof SettingsCatalogRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/scans/$scanId_/review': {
      id: '/scans/$scanId_/review'
      path: '/scans/$scanId/review'
      fullPath: '/scans/$scanId/review'
      preLoaderRoute: typeof ScansScanIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$catalog_/new': {
      id: '/settings/$catalog_/new'
      path: '/$catalog/new'
      fullPath: '/settings/$catalog/new'
      preLoaderRoute: typeof SettingsCatalogNewRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/$catalog_/$entryId/edit': {
      id: '/settings/$catalog_/$entryId/edit'
      path: '/$catalog/$entryId/edit'
      fullPath: '/settings/$catalog/$entryId/edit'
      preLoaderRoute: typeof SettingsCatalogEntryIdEditRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface DocumentsRouteChildren {
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsCatalogRoute: typeof SettingsCatalogRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsCatalogNewRoute: typeof SettingsCatalogNewRoute
  SettingsCatalogEntryIdEditRoute: typeof SettingsCatalogEntryIdEditRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCatalogRoute: SettingsCatalogRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsCatalogNewRoute: SettingsCatalogNewRoute,
  SettingsCatalogEntryIdEditRoute: SettingsCatalogEntryIdEditRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ScansScanIdRoute: ScansScanIdRoute,
  ScansUploadRoute: ScansUploadRoute,
  ScansIndexRoute: ScansIndexRoute,
  ScansScanIdReviewRoute: ScansScanIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
