/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DocumentsTestRouteImport } from './routes/documents-test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembersRouteImport } from './routes/members'
import { Route as NavigationPreviewRouteImport } from './routes/navigation-preview'
import { Route as PipelinePreviewRouteImport } from './routes/pipeline-preview'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ScansRouteImport } from './routes/scans'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents.$documentId'
import { Route as ScansScanIdRouteImport } from './routes/scans.$scanId'
import { Route as ScansUploadRouteImport } from './routes/scans_.upload'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsCatalogRouteImport } from './routes/settings.$catalog'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ScansScanIdReviewRouteImport } from './routes/scans_.$scanId.review'
import { Route as SettingsCatalogNewRouteImport } from './routes/settings.$catalog_.new'
import { Route as SettingsCatalogEntryIdEditRouteImport } from './routes/settings.$catalog_.$entryId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsTestRoute = DocumentsTestRouteImport.update({
  id: '/documents-test',
  path: '/documents-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationPreviewRoute = NavigationPreviewRouteImport.update({
  id: '/navigation-preview',
  path: '/navigation-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinePreviewRoute = PipelinePreviewRouteImport.update({
  id: '/pipeline-preview',
  path: '/pipeline-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansRoute = ScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => DocumentsRoute,
} as any)
const ScansScanIdRoute = ScansScanIdRouteImport.update({
  id: '/$scanId',
  path: '/$scanId',
  getParentRoute: () => ScansRoute,
} as any)
const ScansUploadRoute = ScansUploadRouteImport.update({
  id: '/scans_/upload',
  path: '/scans/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCatalogRoute = SettingsCatalogRouteImport.update({
  id: '/$catalog',
  path: '/$catalog',
  getParentRoute: () => SettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansScanIdReviewRoute = ScansScanIdReviewRouteImport.update({
  id: '/scans_/$scanId/review',
  path: '/scans/$scanId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCatalogNewRoute = SettingsCatalogNewRouteImport.update({
  id: '/$catalog_/new',
  path: '/$catalog/new',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCatalogEntryIdEditRoute =
  SettingsCatalogEntryIdEditRouteImport.update({
    id: '/$catalog_/$entryId/edit',
    path: '/$catalog/$entryId/edit',
    getParentRoute: () => SettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/documents-test': typeof DocumentsTestRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/navigation-preview': typeof NavigationPreviewRoute
  '/pipeline-preview': typeof PipelinePreviewRoute
  '/roadmap': typeof RoadmapRoute
  '/scans': typeof ScansRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/users': typeof UsersRoute
  '/api/$': typeof ApiSplatRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/scans/$scanId': typeof ScansScanIdRoute
  '/scans/upload': typeof ScansUploadRoute
  '/settings/$catalog': typeof SettingsCatalogRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/scans/$scanId/review': typeof ScansScanIdReviewRoute
  '/settings/$catalog/new': typeof SettingsCatalogNewRoute
  '/settings/$catalog/$entryId/edit': typeof SettingsCatalogEntryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/documents-test': typeof DocumentsTestRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/navigation-preview': typeof NavigationPreviewRoute
  '/pipeline-preview': typeof PipelinePreviewRoute
  '/roadmap': typeof RoadmapRoute
  '/scans': typeof ScansRouteWithChildren
  '/users': typeof UsersRoute
  '/api/$': typeof ApiSplatRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/scans/$scanId': typeof ScansScanIdRoute
  '/scans/upload': typeof ScansUploadRoute
  '/settings/$catalog': typeof SettingsCatalogRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/scans/$scanId/review': typeof ScansScanIdReviewRoute
  '/settings/$catalog/new': typeof SettingsCatalogNewRoute
  '/settings/$catalog/$entryId/edit': typeof SettingsCatalogEntryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/documents-test': typeof DocumentsTestRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/navigation-preview': typeof NavigationPreviewRoute
  '/pipeline-preview': typeof PipelinePreviewRoute
  '/roadmap': typeof RoadmapRoute
  '/scans': typeof ScansRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/users': typeof UsersRoute
  '/api/$': typeof ApiSplatRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/scans/$scanId': typeof ScansScanIdRoute
  '/scans_/upload': typeof ScansUploadRoute
  '/settings/$catalog': typeof SettingsCatalogRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/scans_/$scanId/review': typeof ScansScanIdReviewRoute
  '/settings/$catalog_/new': typeof SettingsCatalogNewRoute
  '/settings/$catalog_/$entryId/edit': typeof SettingsCatalogEntryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/documents'
    | '/documents-test'
    | '/login'
    | '/members'
    | '/navigation-preview'
    | '/pipeline-preview'
    | '/roadmap'
    | '/scans'
    | '/settings'
    | '/users'
    | '/api/$'
    | '/documents/$documentId'
    | '/scans/$scanId'
    | '/scans/upload'
    | '/settings/$catalog'
    | '/settings/'
    | '/api/auth/$'
    | '/scans/$scanId/review'
    | '/settings/$catalog/new'
    | '/settings/$catalog/$entryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/documents'
    | '/documents-test'
    | '/login'
    | '/members'
    | '/navigation-preview'
    | '/pipeline-preview'
    | '/roadmap'
    | '/scans'
    | '/users'
    | '/api/$'
    | '/documents/$documentId'
    | '/scans/$scanId'
    | '/scans/upload'
    | '/settings/$catalog'
    | '/settings'
    | '/api/auth/$'
    | '/scans/$scanId/review'
    | '/settings/$catalog/new'
    | '/settings/$catalog/$entryId/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/documents'
    | '/documents-test'
    | '/login'
    | '/members'
    | '/navigation-preview'
    | '/pipeline-preview'
    | '/roadmap'
    | '/scans'
    | '/settings'
    | '/users'
    | '/api/$'
    | '/documents/$documentId'
    | '/scans/$scanId'
    | '/scans_/upload'
    | '/settings/$catalog'
    | '/settings/'
    | '/api/auth/$'
    | '/scans_/$scanId/review'
    | '/settings/$catalog_/new'
    | '/settings/$catalog_/$entryId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  DocumentsTestRoute: typeof DocumentsTestRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  NavigationPreviewRoute: typeof NavigationPreviewRoute
  PipelinePreviewRoute: typeof PipelinePreviewRoute
  RoadmapRoute: typeof RoadmapRoute
  ScansRoute: typeof ScansRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  UsersRoute: typeof UsersRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ScansUploadRoute: typeof ScansUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ScansScanIdReviewRoute: typeof ScansScanIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents-test': {
      id: '/documents-test'
      path: '/documents-test'
      fullPath: '/documents-test'
      preLoaderRoute: typeof DocumentsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation-preview': {
      id: '/navigation-preview'
      path: '/navigation-preview'
      fullPath: '/navigation-preview'
      preLoaderRoute: typeof NavigationPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline-preview': {
      id: '/pipeline-preview'
      path: '/pipeline-preview'
      fullPath: '/pipeline-preview'
      preLoaderRoute: typeof PipelinePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans': {
      id: '/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof ScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/scans/$scanId': {
      id: '/scans/$scanId'
      path: '/$scanId'
      fullPath: '/scans/$scanId'
      preLoaderRoute: typeof ScansScanIdRouteImport
      parentRoute: typeof ScansRoute
    }
    '/scans_/upload': {
      id: '/scans_/upload'
      path: '/scans/upload'
      fullPath: '/scans/upload'
      preLoaderRoute: typeof ScansUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/$catalog': {
      id: '/settings/$catalog'
      path: '/$catalog'
      fullPath: '/settings/$catalog'
      preLoaderRoute: typeof SettingsCatalogRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans_/$scanId/review': {
      id: '/scans_/$scanId/review'
      path: '/scans/$scanId/review'
      fullPath: '/scans/$scanId/review'
      preLoaderRoute: typeof ScansScanIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$catalog_/new': {
      id: '/settings/$catalog_/new'
      path: '/$catalog/new'
      fullPath: '/settings/$catalog/new'
      preLoaderRoute: typeof SettingsCatalogNewRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/$catalog_/$entryId/edit': {
      id: '/settings/$catalog_/$entryId/edit'
      path: '/$catalog/$entryId/edit'
      fullPath: '/settings/$catalog/$entryId/edit'
      preLoaderRoute: typeof SettingsCatalogEntryIdEditRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface DocumentsRouteChildren {
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

interface ScansRouteChildren {
  ScansScanIdRoute: typeof ScansScanIdRoute
}

const ScansRouteChildren: ScansRouteChildren = {
  ScansScanIdRoute: ScansScanIdRoute,
}

const ScansRouteWithChildren = ScansRoute._addFileChildren(ScansRouteChildren)

interface SettingsRouteChildren {
  SettingsCatalogRoute: typeof SettingsCatalogRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsCatalogNewRoute: typeof SettingsCatalogNewRoute
  SettingsCatalogEntryIdEditRoute: typeof SettingsCatalogEntryIdEditRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCatalogRoute: SettingsCatalogRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsCatalogNewRoute: SettingsCatalogNewRoute,
  SettingsCatalogEntryIdEditRoute: SettingsCatalogEntryIdEditRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  DocumentsTestRoute: DocumentsTestRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  NavigationPreviewRoute: NavigationPreviewRoute,
  PipelinePreviewRoute: PipelinePreviewRoute,
  RoadmapRoute: RoadmapRoute,
  ScansRoute: ScansRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  UsersRoute: UsersRoute,
  ApiSplatRoute: ApiSplatRoute,
  ScansUploadRoute: ScansUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ScansScanIdReviewRoute: ScansScanIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
