/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Entry */
        post: operations["create_entry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/{kind}/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Entry */
        put: operations["update_entry"];
        post?: never;
        /** Delete Entry */
        delete: operations["delete_entry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inboxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inboxes */
        get: operations["inboxes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inboxes/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Register Inboxes */
        put: operations["register_inboxes"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inboxes/{inbox_id}/routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Inbox Routing */
        put: operations["inbox_routing"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scans */
        get: operations["scans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan */
        get: operations["scan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan Pdf */
        get: operations["scan_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Scan */
        post: operations["retry_scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocess Scan */
        post: operations["reprocess_scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Approve Scan */
        put: operations["approve_scan"];
        /** Revise Scan */
        post: operations["revise_scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Documents */
        get: operations["documents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document */
        get: operations["document"];
        /** Edit Document */
        put: operations["edit_document"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/confirm-delivery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Delivery */
        post: operations["confirm_delivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Document */
        post: operations["verify_document"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document Pdf */
        get: operations["document_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Document Tags */
        put: operations["document_tags"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enrich */
        post: operations["enrich_document"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document Access */
        get: operations["document_access"];
        /** Deliver Document */
        put: operations["deliver_document"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Settings */
        get: operations["workspace_settings"];
        /** Workspace Preferences */
        put: operations["workspace_preferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Settings */
        get: operations["settings"];
        /** Save Settings */
        put: operations["save_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild */
        post: operations["rebuild_index"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountInbox */
        AccountInbox: {
            /** Account Id */
            account_id: string;
            /** Name */
            name: string;
        };
        /** ActionResult */
        ActionResult: {
            /** Message */
            message: string;
        };
        /** Analysis */
        "Analysis-Input": {
            /** Documents */
            documents: components["schemas"]["DocumentProposal-Input"][];
            /** Page Rotations */
            page_rotations?: components["schemas"]["PageRotation"][];
            /**
             * Blank Pages
             * @description Confirmed blank source pages omitted from filed documents. Originals retain every page.
             */
            blank_pages?: number[];
        };
        /** Analysis */
        "Analysis-Output": {
            /** Documents */
            documents: components["schemas"]["DocumentProposal-Output"][];
            /** Page Rotations */
            page_rotations: components["schemas"]["PageRotation"][];
            /**
             * Blank Pages
             * @description Confirmed blank source pages omitted from filed documents. Originals retain every page.
             */
            blank_pages: number[];
        };
        /** Body_upload */
        Body_upload: {
            /** File */
            file: string;
        };
        /** Catalog */
        Catalog: {
            /** Creators */
            creators: components["schemas"]["CatalogEntry"][];
            /** Owners */
            owners: components["schemas"]["CatalogEntry"][];
            /** Tags */
            tags: components["schemas"]["CatalogEntry"][];
        };
        /** CatalogEntry */
        CatalogEntry: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases: string[];
            /**
             * Icon
             * @default auto
             * @enum {string}
             */
            icon: "auto" | "file" | "receipt" | "shield" | "bank" | "health" | "utilities" | "contract" | "home" | "car" | "business" | "education" | "travel" | "tax";
        };
        /** Creator */
        "Creator-Input": {
            /**
             * Catalog Id
             * @description Existing directory ID, or null for a new creator.
             */
            catalog_id?: string | null;
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
        };
        /** Creator */
        "Creator-Output": {
            /**
             * Catalog Id
             * @description Existing directory ID, or null for a new creator.
             */
            catalog_id: string | null;
            /** Name */
            name: string;
            /** Aliases */
            aliases: string[];
        };
        /** Dashboard */
        Dashboard: {
            /** Routing Documents */
            routing_documents: components["schemas"]["Document"][];
            /** Routing Total */
            routing_total: number;
            /** Documents */
            documents: number;
            /** Pending */
            pending: number;
            /** Review */
            review: number;
            /** Failed */
            failed: number;
            /** Enrichment Failed */
            enrichment_failed: number;
            worker: components["schemas"]["WorkerState"] | null;
            /** Worker Online */
            worker_online: boolean;
            /** Ocr Available */
            ocr_available: boolean;
            /** Model Configured */
            model_configured: boolean;
            /** Inbox Path */
            inbox_path: string;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            pipeline_items: components["schemas"]["PipelinePage"];
            /** Unverified Documents */
            unverified_documents: components["schemas"]["Document"][];
        };
        /** DeliveryConfirmation */
        DeliveryConfirmation: {
            /** Revision */
            revision: number;
        };
        /** Document */
        Document: {
            /** Owner Ids */
            owner_ids: string[];
            /** Creator Ids */
            creator_ids: string[];
            /**
             * Creators Edited
             * @default false
             */
            creators_edited: boolean;
            /**
             * Inbox Id
             * @default shared
             */
            inbox_id: string;
            /** Access User Ids */
            access_user_ids: string[];
            /**
             * Delivery Status
             * @default review
             * @enum {string}
             */
            delivery_status: "review" | "delivered";
            delivery_confirmation: components["schemas"]["Verification"] | null;
            verification: components["schemas"]["Verification"] | null;
            /** Manual Rotations */
            manual_rotations: components["schemas"]["PageRotation"][];
            /** Id */
            id: string;
            /** Scan Id */
            scan_id: string;
            /** Source Pages */
            source_pages: number[];
            /**
             * Processing Run
             * @default 1
             */
            processing_run: number;
            /** Page Rotations */
            page_rotations: components["schemas"]["PageRotation"][];
            /** Title */
            title: string;
            /**
             * Document Date
             * Format: date
             */
            document_date: string;
            /**
             * Date Source
             * @enum {string}
             */
            date_source: "document" | "scan_fallback";
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
            /** Final Path */
            final_path: string;
            /** Processed At */
            processed_at: string | null;
            /** User Tags */
            user_tags: string[];
            /** Excluded Tags */
            excluded_tags: string[];
            /** Generated Tags */
            generated_tags: string[];
            /** Suggested Tags */
            suggested_tags: string[];
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Summary Edited
             * @default false
             */
            summary_edited: boolean;
            /** Text Override */
            text_override: string | null;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /**
             * Pdf Revision
             * @default 0
             */
            pdf_revision: number;
            /** History */
            history: components["schemas"]["Event"][];
            /**
             * Enrichment Status
             * @default pending
             * @enum {string}
             */
            enrichment_status: "pending" | "running" | "complete" | "failed";
            /**
             * Enrichment Version
             * @default
             */
            enrichment_version: string;
            /**
             * Enrichment Error
             * @default
             */
            enrichment_error: string;
            /** Processing */
            processing: components["schemas"]["UsageAllocation"][];
        };
        /** DocumentAccess */
        DocumentAccess: {
            /** User Ids */
            user_ids: string[];
            /** Owner User Id */
            owner_user_id: string | null;
            /** Suggested User Ids */
            suggested_user_ids: string[];
            /** Recipients */
            recipients: components["schemas"]["AccountInbox"][];
            /** Revision */
            revision: number;
        };
        /** DocumentDelivery */
        DocumentDelivery: {
            /** User Ids */
            user_ids: string[];
            /** Revision */
            revision: number;
        };
        /** DocumentDetail */
        DocumentDetail: {
            document: components["schemas"]["Document"];
            /** Text */
            text: string;
            source: components["schemas"]["SourceReference"];
            /** Can Manage Access */
            can_manage_access: boolean;
            /** Can Edit Pages */
            can_edit_pages: boolean;
        };
        /** DocumentEdit */
        DocumentEdit: {
            /** Owner Ids */
            owner_ids: string[];
            /** Creator Ids */
            creator_ids?: string[] | null;
            /** Source Pages */
            source_pages?: number[] | null;
            /** Rotations */
            rotations?: components["schemas"]["PageRotation"][];
            /** Revision */
            revision: number;
            /** Title */
            title: string;
            /** Document Date */
            document_date: string | null;
            /** Summary */
            summary: string;
            /** Tag Ids */
            tag_ids: string[];
            /** Text */
            text: string;
        };
        /** DocumentPage */
        DocumentPage: {
            /** Items */
            items: components["schemas"]["Document"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
        };
        /** DocumentProposal */
        "DocumentProposal-Input": {
            /**
             * Owner Ids
             * @description All catalog IDs matching actual recipients, not senders. Use [unknown] only if no owner matches.
             */
            owner_ids?: string[];
            /**
             * Creators
             * @description People or organizations responsible for the document. Empty for IDs or when attribution is not useful or clear. Include all named authors of a report.
             */
            creators?: components["schemas"]["Creator-Input"][];
            /**
             * Title
             * @description Short, human-readable title with the specific subject and document type. Include a creator or service name only when useful. Preserve a meaningful report title. No recipient, reference number, or date.
             */
            title: string;
            /**
             * Document Date
             * @description Printed issue date, YYYY-MM-DD. Not a deadline or appointment date. Null if absent or uncertain.
             */
            document_date?: string | null;
            /**
             * Confidence
             * @description Confidence from 0 to 1.
             */
            confidence: number;
            /**
             * Review Reason
             * @description Only describe uncertainty that needs review. Empty string when clear.
             * @default
             */
            review_reason: string;
            /**
             * Pages
             * @description One-based source page numbers in original order.
             */
            pages: number[];
        };
        /** DocumentProposal */
        "DocumentProposal-Output": {
            /**
             * Owner Ids
             * @description All catalog IDs matching actual recipients, not senders. Use [unknown] only if no owner matches.
             */
            owner_ids: string[];
            /**
             * Creators
             * @description People or organizations responsible for the document. Empty for IDs or when attribution is not useful or clear. Include all named authors of a report.
             */
            creators: components["schemas"]["Creator-Output"][];
            /**
             * Title
             * @description Short, human-readable title with the specific subject and document type. Include a creator or service name only when useful. Preserve a meaningful report title. No recipient, reference number, or date.
             */
            title: string;
            /**
             * Document Date
             * @description Printed issue date, YYYY-MM-DD. Not a deadline or appointment date. Null if absent or uncertain.
             */
            document_date: string | null;
            /**
             * Confidence
             * @description Confidence from 0 to 1.
             */
            confidence: number;
            /**
             * Review Reason
             * @description Only describe uncertainty that needs review. Empty string when clear.
             * @default
             */
            review_reason: string;
            /**
             * Pages
             * @description One-based source page numbers in original order.
             */
            pages: number[];
        };
        /** DocumentVerify */
        DocumentVerify: {
            /** Revision */
            revision: number;
            /** Reviewer */
            reviewer: string;
        };
        /** EntryInput */
        EntryInput: {
            /** Name */
            name: string;
            /**
             * Icon
             * @default auto
             * @enum {string}
             */
            icon: "auto" | "file" | "receipt" | "shield" | "bank" | "health" | "utilities" | "contract" | "home" | "car" | "business" | "education" | "travel" | "tax";
            /** Aliases */
            aliases?: string[];
        };
        /** EntryRemoval */
        EntryRemoval: {
            /**
             * Status
             * @enum {string}
             */
            status: "removed" | "in_use";
            /** Documents */
            documents: number;
            /** Scans */
            scans: number;
        };
        /** Event */
        Event: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Stage */
            stage: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Inbox */
        Inbox: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Account Id */
            account_id: string | null;
            /** Routing Owner Ids */
            routing_owner_ids: string[];
            /** Time Format */
            time_format: ("24h" | "12h") | null;
        };
        /** InboxRouting */
        InboxRouting: {
            /** Owner Ids */
            owner_ids: string[];
        };
        /** ModelPricing */
        "ModelPricing-Input": {
            /** Model */
            model: string;
            /** Base Url */
            base_url: string;
            /** Input Usd Per Million */
            input_usd_per_million: number | string;
            /** Output Usd Per Million */
            output_usd_per_million: number | string;
            /** Cached Input Usd Per Million */
            cached_input_usd_per_million?: number | string | null;
            /** Source */
            source: string;
            /**
             * Checked On
             * Format: date
             */
            checked_on: string;
        };
        /** ModelPricing */
        "ModelPricing-Output": {
            /** Model */
            model: string;
            /** Base Url */
            base_url: string;
            /** Input Usd Per Million */
            input_usd_per_million: string;
            /** Output Usd Per Million */
            output_usd_per_million: string;
            /** Cached Input Usd Per Million */
            cached_input_usd_per_million: string | null;
            /** Source */
            source: string;
            /**
             * Checked On
             * Format: date
             */
            checked_on: string;
        };
        /** ModelSettings */
        "ModelSettings-Input": {
            /**
             * Provider
             * @default compatible
             * @enum {string}
             */
            provider: "compatible" | "ollama" | "demo";
            /**
             * Reasoning Effort
             * @default default
             * @enum {string}
             */
            reasoning_effort: "default" | "none" | "low" | "medium" | "high";
            /**
             * Base Url
             * @default
             */
            base_url: string;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Timeout Seconds
             * @default 180
             */
            timeout_seconds: number;
            /**
             * Output Mode
             * @default prompted
             * @enum {string}
             */
            output_mode: "prompted" | "native" | "tool";
            pricing?: components["schemas"]["ModelPricing-Input"] | null;
            /**
             * Review Before Filing
             * @default false
             */
            review_before_filing: boolean;
            /**
             * Ocr Languages
             * @default eng
             */
            ocr_languages: string;
            /**
             * Time Format
             * @default 24h
             * @enum {string}
             */
            time_format: "24h" | "12h";
        };
        /** ModelSettings */
        "ModelSettings-Output": {
            /**
             * Provider
             * @default compatible
             * @enum {string}
             */
            provider: "compatible" | "ollama" | "demo";
            /**
             * Reasoning Effort
             * @default default
             * @enum {string}
             */
            reasoning_effort: "default" | "none" | "low" | "medium" | "high";
            /**
             * Base Url
             * @default
             */
            base_url: string;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Timeout Seconds
             * @default 180
             */
            timeout_seconds: number;
            /**
             * Output Mode
             * @default prompted
             * @enum {string}
             */
            output_mode: "prompted" | "native" | "tool";
            pricing: components["schemas"]["ModelPricing-Output"] | null;
            /**
             * Review Before Filing
             * @default false
             */
            review_before_filing: boolean;
            /**
             * Ocr Languages
             * @default eng
             */
            ocr_languages: string;
            /**
             * Time Format
             * @default 24h
             * @enum {string}
             */
            time_format: "24h" | "12h";
        };
        /** PageRotation */
        PageRotation: {
            /**
             * Page
             * @description One-based source page number.
             */
            page: number;
            /**
             * Clockwise
             * @description Clockwise correction needed to make the supplied page image upright.
             * @enum {integer}
             */
            clockwise: 90 | 180 | 270;
        };
        /** PipelineDocumentItem */
        PipelineDocumentItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "review" | "failed" | "complete";
            /** Detail */
            detail: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "document";
            document: components["schemas"]["Document"];
        };
        /** PipelinePage */
        PipelinePage: {
            /** Status */
            status: ("queued" | "running" | "review" | "failed" | "complete") | "unverified";
            /** Items */
            items: (components["schemas"]["PipelineScanItem"] | components["schemas"]["PipelineDocumentItem"])[];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
        };
        /** PipelineScanItem */
        PipelineScanItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "review" | "failed" | "complete";
            /** Detail */
            detail: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "scan";
        };
        /** PipelineStep */
        PipelineStep: {
            /**
             * Id
             * @enum {string}
             */
            id: "inbox" | "ocr" | "analyze" | "review" | "file" | "tag" | "ready";
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "review" | "failed" | "complete";
            /** Detail */
            detail: string;
            /** Count */
            count: number | null;
        };
        /** ProcessingUsage */
        ProcessingUsage: {
            /** Id */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "ocr" | "split" | "details" | "tagging" | "review" | "transcription";
            /** Source Pages */
            source_pages: number[];
            /** Model */
            model: string;
            /** Base Url */
            base_url: string;
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "failed";
            /** Seconds */
            seconds: number;
            /**
             * Requests
             * @default 0
             */
            requests: number;
            /** Input Tokens */
            input_tokens: number | null;
            /** Cached Input Tokens */
            cached_input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Token Details */
            token_details: {
                [key: string]: number;
            };
            /**
             * Usage Complete
             * @default false
             */
            usage_complete: boolean;
            pricing: components["schemas"]["ModelPricing-Output"] | null;
            /** Estimated Cost Usd */
            estimated_cost_usd: string | null;
        };
        /** Scan */
        Scan: {
            /** Id */
            id: string;
            /**
             * Inbox Id
             * @default shared
             */
            inbox_id: string;
            /** Content Hash */
            content_hash: string;
            /** Original Name */
            original_name: string;
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
            /**
             * Timestamp Source
             * @default file_mtime
             * @enum {string}
             */
            timestamp_source: "file_mtime" | "upload";
            /** Arrivals */
            arrivals: string[];
            /**
             * Page Count
             * @default 0
             */
            page_count: number;
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "queued" | "running" | "review" | "failed" | "complete";
            /**
             * Phase
             * @default analyze
             * @enum {string}
             */
            phase: "ocr" | "analyze" | "file" | "done";
            /** Ocr Rotations */
            ocr_rotations: components["schemas"]["PageRotation"][] | null;
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            proposal: components["schemas"]["Analysis-Output"] | null;
            /** Document Ids */
            document_ids: string[];
            /**
             * Filing Revision
             * @default 0
             */
            filing_revision: number;
            /**
             * Processing Run
             * @default 1
             */
            processing_run: number;
            /** Filing Paths */
            filing_paths: {
                [key: string]: string;
            };
            /** History */
            history: components["schemas"]["Event"][];
            /** Processing */
            processing: components["schemas"]["ScanUsage"][];
        };
        /** ScanDetail */
        ScanDetail: {
            /** Id */
            id: string;
            /**
             * Inbox Id
             * @default shared
             */
            inbox_id: string;
            /** Content Hash */
            content_hash: string;
            /** Original Name */
            original_name: string;
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
            /**
             * Timestamp Source
             * @default file_mtime
             * @enum {string}
             */
            timestamp_source: "file_mtime" | "upload";
            /** Arrivals */
            arrivals: string[];
            /**
             * Page Count
             * @default 0
             */
            page_count: number;
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "queued" | "running" | "review" | "failed" | "complete";
            /**
             * Phase
             * @default analyze
             * @enum {string}
             */
            phase: "ocr" | "analyze" | "file" | "done";
            /** Ocr Rotations */
            ocr_rotations: components["schemas"]["PageRotation"][] | null;
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            proposal: components["schemas"]["Analysis-Output"] | null;
            /** Document Ids */
            document_ids: string[];
            /**
             * Filing Revision
             * @default 0
             */
            filing_revision: number;
            /**
             * Processing Run
             * @default 1
             */
            processing_run: number;
            /** Filing Paths */
            filing_paths: {
                [key: string]: string;
            };
            /** History */
            history: components["schemas"]["Event"][];
            /** Processing */
            processing: components["schemas"]["ScanUsage"][];
            /** Pipeline */
            pipeline: components["schemas"]["PipelineStep"][];
        };
        /** ScanFeedback */
        ScanFeedback: {
            proposal: components["schemas"]["Analysis-Input"];
            /** Instructions */
            instructions: string;
        };
        /** ScanPage */
        ScanPage: {
            /** Items */
            items: components["schemas"]["Scan"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
        };
        /** ScanReprocess */
        ScanReprocess: {
            /** Filing Revision */
            filing_revision: number;
            /** Document Revisions */
            document_revisions: {
                [key: string]: number;
            };
        };
        /** ScanReview */
        ScanReview: {
            /** Documents */
            documents: components["schemas"]["DocumentProposal-Input"][];
            /** Page Rotations */
            page_rotations?: components["schemas"]["PageRotation"][];
            /**
             * Blank Pages
             * @description Confirmed blank source pages omitted from filed documents. Originals retain every page.
             */
            blank_pages?: number[];
            /** Document Revisions */
            document_revisions?: {
                [key: string]: number;
            };
        };
        /** ScanUsage */
        ScanUsage: {
            /** Id */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "ocr" | "split" | "details" | "tagging" | "review" | "transcription";
            /** Source Pages */
            source_pages: number[];
            /** Model */
            model: string;
            /** Base Url */
            base_url: string;
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "failed";
            /** Seconds */
            seconds: number;
            /**
             * Requests
             * @default 0
             */
            requests: number;
            /** Input Tokens */
            input_tokens: number | null;
            /** Cached Input Tokens */
            cached_input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Token Details */
            token_details: {
                [key: string]: number;
            };
            /**
             * Usage Complete
             * @default false
             */
            usage_complete: boolean;
            pricing: components["schemas"]["ModelPricing-Output"] | null;
            /** Estimated Cost Usd */
            estimated_cost_usd: string | null;
            /**
             * Processing Run
             * @default 1
             */
            processing_run: number;
        };
        /** SourceReference */
        SourceReference: {
            /** Scan Id */
            scan_id: string;
            /**
             * Inbox
             * @enum {string}
             */
            inbox: "personal" | "shared";
            /** Accessible */
            accessible: boolean;
        };
        /** TagSelection */
        TagSelection: {
            /** Tag Ids */
            tag_ids: string[];
        };
        /** UsageAllocation */
        UsageAllocation: {
            call: components["schemas"]["ProcessingUsage"];
            /** Share */
            share: string;
            /** Estimated Cost Usd */
            estimated_cost_usd: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Verification */
        Verification: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** By */
            by: string;
        };
        /** WorkerState */
        WorkerState: {
            /**
             * Heartbeat
             * Format: date-time
             */
            heartbeat: string;
            /**
             * Status
             * @enum {string}
             */
            status: "idle" | "working" | "error" | "stopped";
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** WorkspacePreferences */
        WorkspacePreferences: {
            /**
             * Time Format
             * @enum {string}
             */
            time_format: "24h" | "12h";
        };
        /** WorkspaceSettings */
        WorkspaceSettings: {
            /**
             * Time Format
             * @enum {string}
             */
            time_format: "24h" | "12h";
            /** Demo */
            demo: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    catalog: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entry: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                kind: "owners" | "tags" | "creators";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entry: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                kind: "owners" | "tags" | "creators";
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entry: {
        parameters: {
            query?: {
                reassign_to?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                kind: "owners" | "tags" | "creators";
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryRemoval"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inboxes: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inbox"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_inboxes: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountInbox"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inbox"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inbox_routing: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                inbox_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboxRouting"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inbox"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scans: {
        parameters: {
            query?: {
                status?: string;
                q?: string;
                inbox?: string;
                page?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_pdf: {
        parameters: {
            query?: {
                variant?: "original" | "searchable";
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_scan: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_scan: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanReprocess"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_scan: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_scan: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanFeedback"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: {
                inbox?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    documents: {
        parameters: {
            query?: {
                q?: string;
                owner?: string[] | null;
                tag?: string[] | null;
                creator?: string[] | null;
                status?: string;
                delivery?: "" | "review" | "delivered";
                inbox?: string;
                after?: string | null;
                before?: string | null;
                sort?: "date_desc" | "date_asc" | "title" | "title_desc" | "creators_asc" | "creators_desc" | "owners_asc" | "owners_desc" | "tags_asc" | "tags_desc" | "verification_asc" | "verification_desc" | "delivery_asc" | "delivery_desc" | "processed_asc" | "processed_desc";
                page?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_document: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_delivery: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryConfirmation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_document: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentVerify"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_pdf: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_tags: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagSelection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enrich_document: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_access: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentAccess"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deliver_document: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentDelivery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_settings: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_preferences: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspacePreferences"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard: {
        parameters: {
            query?: {
                status?: ("queued" | "running" | "review" | "failed" | "complete") | "unverified";
                page?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSettings-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_settings: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelSettings-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSettings-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_index: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
